# Use the official MongoDB Docker image
FROM mongo:latest

# Set the working directory to the MongoDB data directory
WORKDIR /data/db

# Expose the MongoDB port
EXPOSE 27017

# Start the MongoDB server
CMD ["mongod"]